# Generated by Django 5.1.6 on 2025-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supercar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30, null=True)),
                ('car_model', models.CharField(max_length=30, null=True)),
                ('brand_country', models.CharField(max_length=30, null=True)),
                ('release_date', models.DateField(null=True)),
                ('max_speed', models.IntegerField(null=True)),
                ('engine_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
